Feature/corutines network layer
rootstrap/android-base pull request #36
Opened 2020-12-16 21:09 UTC by amaury901130

### Description
- Proposal coroutines on the network layer, over the ViewModelScope

Official doc: 
https://developer.android.com/topic/libraries/architecture/coroutines

Issue: [Add Kotlin Coroutines](https://github.com/rootstrap/android-base/issues/22)

2020-12-17 14:42 UTC, ximenaperez commented on app/src/main/java/com/rootstrap/android/ui/activity/main/SignInActivityViewModel.kt
> +    private fun mangeError(exception: Throwable?) {
there's a typo in the method name, it should be manageError

2020-12-17 14:58 UTC, ximenaperez commented on app/src/main/java/com/rootstrap/android/ui/activity/main/SignUpActivityViewModel.kt
> +    private fun mangeError(exception: Throwable?) {
same here

2020-12-17 14:59 UTC, ximenaperez commented on app/src/main/java/com/rootstrap/android/util/extensions/ActionCallback.kt
> +    uknownError
there's a typo here, it should be "unknown"

2020-12-17 15:00 UTC, ximenaperez requested changes
Just a few typos to fix

2020-12-17 16:55 UTC, ximenaperez approved these changes

2020-12-18 14:36 UTC, mato2593 approved these changes

2020-12-18 14:36 UTC, mato2593 commented on app/src/main/java/com/rootstrap/android/util/extensions/ActionCallback.kt
> +        private fun <T> manageResponse(response: Response<T>): Result<Data<T>> {
IMO, `handleResponse` is a more accurate name of what we are doing here. The same would apply for the other `manageSomething` functions.

2020-12-18 14:36 UTC, mato2593 commented on app/src/main/java/com/rootstrap/android/ui/activity/main/SignUpActivityViewModel.kt
> +                state = SignUpState.signedUpSuccess
I know this is old, but it should be either `signUpSuccess` or `signedUpSuccessfully`.

2020-12-18 15:13 UTC, merged